apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-app
    spec:
      containers:
      - name: demo-app
        image: acrthp.azurecr.io/demo-app:2
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: appsecret
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000         
  selector:
    app.kubernetes.io/name: demo-app

